# .miserc.toml = first config read by mise 
#
# This config will load first IFF placed in the correct place.
# This config is not read when in goclaw/mise/miserc.toml
#
# To enable podman environment move to a parent directory
# $> cp goclaw/mise/miserc.toml goclaw/.miserc.toml

env=["podman"]

