[storage]

driver = "overlay"

# We pick /opt since it is outside of zfs
# for running the overlay fs at full speed

rootless_storage_path="/opt/storage"

# howerver we set the volume_path (in containers.conf)
# to /srv which we have managed by zfs for efficient
# snapshot backups of user data
